### PR TITLE
Added development branch notes

### PR DESCRIPTION
**Pull request by joshmagora**
# Pull Request
## Changes
- *I added some text files for notes on development branch*
## Place to start
- *It's on the root folder titled `development branch.txt`*

### CODE REVIEW

**Review by edilsalvador — CHANGES_REQUESTED** [review]
At least input some description on the text file so that every one would know. And please add it on the docs folder. Thanks :+1:

**Comment by joshmagora** [comment]
Hi @edilsalvador, I changed the txt files according to your feedback. Could you review it?

**Review by edilsalvador — CHANGES_REQUESTED** [review]
Oh, last thing. Can you change the name and file type to *DEVELOPMENT.md*

**Comment by joshmagora** [comment]
Hi @edilsalvador, I updated the developer branch according to your request. Could you review it?

**Review by edilsalvador — APPROVED** [review]

**Review by edilsalvador — APPROVED** [review]
LGTM, will merge this one! :+1: :100:

**Pull request merged**
